#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 25 13:39:51 2020

@author: anne
"""


class Animal:
    def __init__(self,HP):
        self.HP = HP
        self.H = 90
        self.w = 30
    def hurt(self,damage):
        self.HP -= damage
        print("剩下血量" + str(self.HP))
        
class cat(Animal):
    def __init__(self,HP):
        super().__init__(HP)
        

        
class ScottishFold(cat):
    def __init__(self):
        super().__init__(1)
        
    def Roar(self):
        print("喵")
        
cat = ScottishFold()
cat.Roar()        