#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 18 14:39:05 2020

@author: anne
"""

class Animal:
    def __init__(self,HP):
        self.HP = HP
    def hurt(self,damage):
        self.HP -= damage
        print("剩下血量" + str(self.HP))
        
class Dog(Animal):
    def __init__(self,HP):
        super().__init__(HP)
        
class ShibaInu(Dog):
    def __init__(self):
        super().__init__(1)

        
    def Roar(self):
        print("旺旺")
        
class Husky(Dog):
    def __init__(self):
        super().__init__(1)
        
    def Roar(self):
        print("阿嗚")
        
dog = ShibaInu()
dog.Roar()        